resources:
- name: testgit-pipelines
  type: git
  source:
    uri: git@github.com:pivotal-jleung/testgit-pipelines.git
    branch: master
    private_key: {{git_private_key}}
- name: schedule
  type: time
  source:
    interval: 30m
    start: "12:00 AM"
    stop: "11:59 PM"
    location: America/Los_Angeles
    days: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]

jobs:
- name: deployed-products
  serial: true
  plan:
  - aggregate:
    - get: testgit-pipelines
    - get: schedule
      trigger: true
  - task: deployed-products
    file: testgit-pipelines/tasks/deployed-products/task.yml
    params:
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}