---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs


inputs:
  - name: testgit-pipelines

params:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:

run:
  path: testgit-pipelines/tasks/deployed-products/task.sh